---
- hosts: gcp_role_web
  name: Install Apache on the web servers
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        name:
          - apache2
          - php

    - name: Create a ext4 filesystem for data
      community.general.filesystem:
        fstype: ext4
        dev: /dev/disk/by-id/google-data

    - name: Mount extra disk
      ansible.posix.mount:
        path: /var/lib/postgresql
        src: /dev/disk/by-id/google-data
        fstype: ext4
        state: present

    - name: Update index.html so we can see the difference between hosts 
      blockinfile:
        path: /var/www/html/index.html
        owner: www-data 
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        insertafter: <body> 
        block: | 
          <h1>This is the server {{ inventory_hostname }}</h1>
          
    - name: Create the health check file. 
      copy:
        dest: /var/www/html/health.html
        content: |
          I'm alive