---
- hosts: all
  name: Add cis-91 packages
  become: yes
  tasks:

    - name: Create a ext4 filesystem for dokuwiki
      community.general.filesystem:
        fstype: ext2
        dev: /dev/disk/by-id/google-data

    - name: Mount extra disk
      ansible.posix.mount:
        path: /var/www
        src: /dev/disk/by-id/google-data
        fstype: ext4
        state: present

    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - nginx
          - apache2
          - php 
          - php-xml

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/eli6679/cis-91/dokuwiki/backup
        dest: /etc/cron.hourly
        owner: root
        group: root
        mode: '0644'
