---
- hosts: all
  name: Add cis-91 packages
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - nginx
          - apache2
          - php 
          - php-xml


    - name: Create a ext4 filesystem for lab09
      community.general.filesystem:
        fstype: ext2
        dev: /dev/disk/by-id/google-lab09

    - name: Mount extra disk
      ansible.posix.mount:
        path: /var/www
        src: /dev/disk/by-id/google-lab09
        fstype: ext4
        state: present